# Generated by Django 4.2.7 on 2025-10-02 07:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CropType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('emoji', models.CharField(default='🌱', max_length=10)),
                ('seed_price', models.IntegerField()),
                ('sell_price', models.IntegerField()),
                ('growth_time_minutes', models.IntegerField()),
                ('experience_reward', models.IntegerField(default=1)),
                ('min_level_required', models.IntegerField(default=1)),
                ('energy_cost', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['min_level_required', 'growth_time_minutes'],
            },
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=1)),
                ('experience', models.IntegerField(default=0)),
                ('energy', models.IntegerField(default=100)),
                ('max_energy', models.IntegerField(default=100)),
                ('last_energy_update', models.DateTimeField(auto_now=True)),
                ('plots_unlocked', models.IntegerField(default=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='farm', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FarmTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('seed_purchase', 'Seed Purchase'), ('crop_harvest', 'Crop Harvest'), ('plot_unlock', 'Plot Unlock'), ('farm_upgrade', 'Farm Upgrade')], max_length=20)),
                ('amount', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('crop_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='happy_farm.croptype')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='happy_farm.farm')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['farm', '-created_at'], name='happy_farm__farm_id_e1b14d_idx'), models.Index(fields=['transaction_type', '-created_at'], name='happy_farm__transac_8bee75_idx')],
            },
        ),
        migrations.CreateModel(
            name='FarmPlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot_number', models.IntegerField()),
                ('state', models.CharField(choices=[('empty', 'Empty'), ('planted', 'Planted'), ('ready', 'Ready to Harvest'), ('withered', 'Withered')], default='empty', max_length=20)),
                ('planted_at', models.DateTimeField(blank=True, null=True)),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
                ('withers_at', models.DateTimeField(blank=True, null=True)),
                ('crop_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='happy_farm.croptype')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plots', to='happy_farm.farm')),
            ],
            options={
                'indexes': [models.Index(fields=['farm', 'plot_number'], name='happy_farm__farm_id_ec754e_idx'), models.Index(fields=['state'], name='happy_farm__state_b0382b_idx'), models.Index(fields=['ready_at'], name='happy_farm__ready_a_484663_idx')],
                'unique_together': {('farm', 'plot_number')},
            },
        ),
        migrations.AddIndex(
            model_name='farm',
            index=models.Index(fields=['user'], name='happy_farm__user_id_3c4c27_idx'),
        ),
        migrations.AddIndex(
            model_name='farm',
            index=models.Index(fields=['level'], name='happy_farm__level_4ca7b3_idx'),
        ),
    ]
