# Generated by Django 4.2.7 on 2025-10-24 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caro_game', '0002_caromove_remove_roomcarogame_player1_and_more'),
        ('user_wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='caro_game.carogame'),
        ),
    ]
