# Generated by Django 4.2.7 on 2025-10-21 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='privatechat',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Cuộc hội thoại riêng', 'verbose_name_plural': 'Danh sách hội thoại riêng'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['-created_at'], 'verbose_name': 'Hồ sơ người dùng', 'verbose_name_plural': 'Danh sách hồ sơ người dùng'},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, max_length=500, verbose_name='Tiểu sử'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='display_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tên hiển thị'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_online',
            field=models.BooleanField(default=False, verbose_name='Trực tuyến'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_seen',
            field=models.DateTimeField(auto_now=True, verbose_name='Lần cuối trực tuyến'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='total_games_played',
            field=models.IntegerField(default=0, verbose_name='Tổng số trận đã chơi'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='total_games_won',
            field=models.IntegerField(default=0, verbose_name='Tổng số trận thắng'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='total_messages_sent',
            field=models.IntegerField(default=0, verbose_name='Tổng số tin nhắn đã gửi'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối'),
        ),
    ]
