# Generated by Django 4.2.7 on 2025-10-02 07:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomCaroGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(db_index=True, max_length=100)),
                ('game_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('board_state', models.TextField(default='[]')),
                ('current_turn', models.CharField(default='X', max_length=20)),
                ('status', models.CharField(choices=[('waiting', 'Waiting for Player'), ('playing', 'In Progress'), ('finished', 'Finished'), ('abandoned', 'Abandoned')], db_index=True, default='waiting', max_length=10)),
                ('bet_amount', models.IntegerField(default=10000)),
                ('total_pot', models.IntegerField(default=0)),
                ('winner_prize', models.IntegerField(default=0)),
                ('house_fee', models.IntegerField(default=0)),
                ('board_size', models.IntegerField(default=15)),
                ('win_condition', models.IntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('total_moves', models.IntegerField(default=0)),
                ('game_duration', models.DurationField(blank=True, null=True)),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_caro_games_as_player1', to=settings.AUTH_USER_MODEL)),
                ('player2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_caro_games_as_player2', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='won_room_caro_games', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['room_name', 'status'], name='caro_game_r_room_na_f9eeca_idx'), models.Index(fields=['game_id'], name='caro_game_r_game_id_501b64_idx'), models.Index(fields=['player1', '-created_at'], name='caro_game_r_player1_39a28c_idx'), models.Index(fields=['player2', '-created_at'], name='caro_game_r_player2_80e530_idx'), models.Index(fields=['status', '-created_at'], name='caro_game_r_status_00e28c_idx')],
            },
        ),
        migrations.CreateModel(
            name='CaroGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(db_index=True, max_length=100)),
                ('game_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('board_state', models.TextField(default='[]')),
                ('current_turn', models.CharField(default='X', max_length=20)),
                ('status', models.CharField(choices=[('waiting', 'Waiting for Player'), ('playing', 'In Progress'), ('finished', 'Finished'), ('abandoned', 'Abandoned')], db_index=True, default='waiting', max_length=10)),
                ('board_size', models.IntegerField(default=15)),
                ('win_condition', models.IntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('total_moves', models.IntegerField(default=0)),
                ('game_duration', models.DurationField(blank=True, null=True)),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caro_games_as_player1', to=settings.AUTH_USER_MODEL)),
                ('player2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='caro_games_as_player2', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='won_caro_games', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['chat_id', 'status'], name='caro_game_c_chat_id_a64b20_idx'), models.Index(fields=['game_id'], name='caro_game_c_game_id_228a9f_idx'), models.Index(fields=['player1', '-created_at'], name='caro_game_c_player1_daf79f_idx'), models.Index(fields=['player2', '-created_at'], name='caro_game_c_player2_1b6711_idx'), models.Index(fields=['status', '-created_at'], name='caro_game_c_status_2024bb_idx')],
            },
        ),
    ]
