# Generated by Django 4.2.7 on 2025-10-24 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caro_game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaroMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField()),
                ('col', models.IntegerField()),
                ('symbol', models.CharField(max_length=1)),
                ('move_number', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['move_number'],
            },
        ),
        migrations.RemoveField(
            model_name='roomcarogame',
            name='player1',
        ),
        migrations.RemoveField(
            model_name='roomcarogame',
            name='player2',
        ),
        migrations.RemoveField(
            model_name='roomcarogame',
            name='winner',
        ),
        migrations.RemoveIndex(
            model_name='carogame',
            name='caro_game_c_chat_id_a64b20_idx',
        ),
        migrations.RemoveField(
            model_name='carogame',
            name='board_size',
        ),
        migrations.RemoveField(
            model_name='carogame',
            name='board_state',
        ),
        migrations.AddField(
            model_name='carogame',
            name='bet_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='carogame',
            name='game_type',
            field=models.CharField(choices=[('private', 'Private Chat Game'), ('room', 'Room Game')], db_index=True, default='private', max_length=10),
        ),
        migrations.AddField(
            model_name='carogame',
            name='house_fee',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='carogame',
            name='total_pot',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='carogame',
            name='winner_prize',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='carogame',
            index=models.Index(fields=['game_type', 'chat_id', 'status'], name='caro_game_c_game_ty_20b2dd_idx'),
        ),
    ]
