# Generated by Django 4.2.7 on 2025-10-24 02:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caro_game', '0002_caromove_remove_roomcarogame_player1_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_wallet', '0002_alter_wallettransaction_game'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoomCaroGame',
        ),
        migrations.AddField(
            model_name='caromove',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='caro_game.carogame'),
        ),
        migrations.AddField(
            model_name='caromove',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='caromove',
            index=models.Index(fields=['game', 'move_number'], name='caro_game_c_game_id_f38bde_idx'),
        ),
    ]
