# Generated by Django 4.2.7 on 2025-10-24 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caro_game', '0003_delete_roomcarogame_caromove_game_caromove_player_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='carogame',
            name='caro_game_c_game_ty_20b2dd_idx',
        ),
        migrations.RenameField(
            model_name='carogame',
            old_name='chat_id',
            new_name='room_name',
        ),
        migrations.RemoveField(
            model_name='carogame',
            name='game_type',
        ),
        migrations.AlterField(
            model_name='carogame',
            name='bet_amount',
            field=models.IntegerField(default=10000),
        ),
        migrations.AddIndex(
            model_name='carogame',
            index=models.Index(fields=['room_name', 'status'], name='caro_game_c_room_na_00c037_idx'),
        ),
    ]
